"""empty message

Revision ID: 2ae9bd170f33
Revises: 39eed581a272
Create Date: 2025-08-20 20:01:43.584226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae9bd170f33'
down_revision = '39eed581a272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character__film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_character', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_film', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'character', ['id_character'], ['id'])
        batch_op.create_foreign_key(None, 'film', ['id_film'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character__film', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_film')
        batch_op.drop_column('id_character')

    # ### end Alembic commands ###
