"""empty message

Revision ID: 39eed581a272
Revises: 3fdb632f707f
Create Date: 2025-08-20 20:00:22.731893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39eed581a272'
down_revision = '3fdb632f707f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character__vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_character', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_vehicle', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'character', ['id_character'], ['id'])
        batch_op.create_foreign_key(None, 'vehicle', ['id_vehicle'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character__vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_vehicle')
        batch_op.drop_column('id_character')

    # ### end Alembic commands ###
