"""empty message

Revision ID: 4b82891c9b8e
Revises: 2ae9bd170f33
Create Date: 2025-08-21 00:49:10.508983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b82891c9b8e'
down_revision = '2ae9bd170f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite__planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_planet', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_planet'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite__character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_character', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_character'], ['character.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('character__vehicle')
    op.drop_table('character__film')
    op.drop_table('vehicle')
    op.drop_table('film')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('film_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('episode', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='film_pkey'),
    sa.UniqueConstraint('episode', name='film_episode_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('vehicle',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('vehicle_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('passangers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lenght', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('favorite', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='vehicle_pkey'),
    sa.UniqueConstraint('name', name='vehicle_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('character__film',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_character', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_film', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_character'], ['character.id'], name='character__film_id_character_fkey'),
    sa.ForeignKeyConstraint(['id_film'], ['film.id'], name='character__film_id_film_fkey'),
    sa.PrimaryKeyConstraint('id', name='character__film_pkey')
    )
    op.create_table('character__vehicle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_character', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_vehicle', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_character'], ['character.id'], name='character__vehicle_id_character_fkey'),
    sa.ForeignKeyConstraint(['id_vehicle'], ['vehicle.id'], name='character__vehicle_id_vehicle_fkey'),
    sa.PrimaryKeyConstraint('id', name='character__vehicle_pkey')
    )
    op.drop_table('favorite__character')
    op.drop_table('favorite__planet')
    # ### end Alembic commands ###
